import { TestBed } from '@angular/core/testing';
import { AppModule } from './app.module';
import { OVERLAY_WINDOW } from './overlay-navigation';
import { AppComponent } from './app.component';
import { AppUpdates, draftStore } from './app-updates';

describe('Photo studio', () => {
    beforeEach(async () => { await TestBed.configureTestingModule({ imports: [AppModule], providers: [{ provide: OVERLAY_WINDOW, useValue: { history: { state: null, pushState() {}, back() {} }, addEventListener() {}, removeEventListener() {} } }] }).compileComponents(); });
    it('renders named controls and prevents exporting before a frame exists', () => {
        const fixture = TestBed.createComponent(AppComponent);
        spyOn(fixture.componentInstance, 'ngAfterViewInit');
        fixture.detectChanges();
        const root = fixture.nativeElement as HTMLElement;
        expect(root.querySelector('h1')?.textContent).toBe('#TurboPixel');
        expect(root.querySelector('input[type=file]')).not.toBeNull();
        expect(root.querySelector('[aria-label="Next effect"]')).not.toBeNull();
        expect((root.querySelector('.capture-button') as HTMLButtonElement).disabled).toBeTrue();
        fixture.destroy();
    });
    it('wraps palette navigation in both directions', () => {
        const fixture = TestBed.createComponent(AppComponent);
        const app = fixture.componentInstance;
        app.clickBeforeEffect();
        expect(app.selectedEffect).toBe(app.effects.length - 1);
        app.clickNextEffect();
        expect(app.selectedEffect).toBe(0);
        fixture.destroy();
    });
    it('restores the source photo and effect after an update, then removes the temporary draft', async () => {
        const fixture = TestBed.createComponent(AppComponent), app = fixture.componentInstance;
        spyOn(app, 'ngAfterViewInit'); fixture.detectChanges();
        const source = document.createElement('canvas'); source.width = 2; source.height = 2;
        source.getContext('2d')!.fillStyle = '#ff0000'; source.getContext('2d')!.fillRect(0, 0, 2, 2);
        const photo = new Image(); photo.src = source.toDataURL(); await photo.decode();
        app.sourceImage = photo; app.hasFrame = true; app.selectedEffect = 7; app.effectValue = .375;
        const updates = TestBed.inject(AppUpdates); updates.ready = true;
        const reload = spyOn(updates, 'reload'); await app.updateApp();
        expect(reload).toHaveBeenCalledTimes(1); fixture.destroy();
        const restored = TestBed.createComponent(AppComponent), next = restored.componentInstance;
        spyOn(next, 'ngAfterViewInit'); spyOn(next, 'resumePreview'); restored.detectChanges();
        await (next as any).restoreUpdateDraft();
        expect(next.sourceImage!.naturalWidth).toBe(2); expect(next.selectedEffect).toBe(7); expect(next.effectValue).toBe(.375);
        source.getContext('2d')!.drawImage(next.sourceImage!, 0, 0);
        expect([...source.getContext('2d')!.getImageData(0, 0, 1, 1).data]).toEqual([255, 0, 0, 255]);
        expect(await draftStore('read')).toBeUndefined(); restored.destroy();
    });
    it('crossfades palette changes without putting the transition into image data', () => {
        const fixture = TestBed.createComponent(AppComponent);
        const app = fixture.componentInstance;
        spyOn(app, 'ngAfterViewInit'); fixture.detectChanges();
        app.hasFrame = true;
        app.appearance.still = false;
        spyOn(window, 'matchMedia').and.returnValue({ matches: false } as MediaQueryList);
        const transition = app.transitionCanvas.nativeElement;
        const animate = spyOn(transition, 'animate').and.returnValue({ cancel() {} } as Animation);
        app.changeEffect(1, .3);
        expect(app.effectValue).toBe(.3);
        expect(animate).toHaveBeenCalledTimes(1);
        expect(transition.getAttribute('aria-hidden')).toBe('true');
        app.appearance.still = true; app.hasFrame = true;
        app.changeEffect(2);
        expect(animate).toHaveBeenCalledTimes(1);
        fixture.destroy();
    });
    it('retains dialog semantics and backdrop with custom motion durations', async () => {
        const fixture = TestBed.createComponent(AppComponent);
        spyOn(fixture.componentInstance, 'ngAfterViewInit'); fixture.detectChanges();
        fixture.componentInstance.clickAppearance(); fixture.detectChanges();
        await fixture.whenStable();
        const dialog = document.querySelector('[role="dialog"]')!;
        expect(dialog).not.toBeNull();
        expect(dialog.textContent).toContain('Appearance');
        expect(document.querySelector('.cdk-overlay-backdrop')).not.toBeNull();
        (dialog.querySelector('.sheet-done') as HTMLButtonElement).click();
        fixture.destroy();
    });
    it('styles the actual palette container in dark mode, not its overlay parent', async () => {
        const fixture = TestBed.createComponent(AppComponent);
        spyOn(fixture.componentInstance, 'ngAfterViewInit');
        fixture.detectChanges();
        document.documentElement.dataset['style'] = 'modern';
        document.documentElement.dataset['theme'] = 'dark';
        fixture.componentInstance.clickOpenBottomSheetEffect();
        fixture.detectChanges(); await fixture.whenStable();
        const sheet = document.querySelector('.palette-sheet .mat-bottom-sheet-container') as HTMLElement;
        expect(sheet).not.toBeNull();
        const style = getComputedStyle(sheet);
        expect(style.backgroundColor).not.toBe('rgb(255, 255, 255)');
        expect(style.color).toBe('rgb(245, 247, 255)');
        expect(parseFloat(style.borderTopLeftRadius)).toBe(32);
        (sheet.querySelector('.sheet-done') as HTMLButtonElement).click();
        fixture.destroy(); delete document.documentElement.dataset['theme']; delete document.documentElement.dataset['style'];
    });
});
